channels:
    - conda-forge
    - bioconda
dependencies:
    - python
    - ipython
    - jupyter
    - snakemake
    - numpy
    - pandas
    - scipy
    - matplotlib
    - seaborn
    - scanpy
    - rpy2
    - scikit-learn
    - memory_profiler
    - r:r
    - r:r-numDeriv
    - r:r-mvtnorm
    - r:r-Matrix
    - r:r-softImpute
    - r-biocmanager
    - r-sceasy
    - r-devtools
    - r-seurat
    - r-sctransform
    - bioconductor-glmgampoi
    - bioconductor-transformgampoi
    - bioconductor-scran
    - bioconductor-clusterprofiler
    - bioconductor-annotationhub
    #- bioconductor-deseq2
    #- python=3.11.3
    #- snakemake=7.25.0
    #- numpy=1.24.3
    #- pandas=2.0.1
    #- scipy=1.10.1
    #- matplotlib=3.7.1
    #- seaborn=0.12.2
    #- rpy2=3.5.11
    #- ipython=8.12.0
    #- memory_profiler=0.58.0
